# Generated by Django 6.0.7 on 2026-10-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('planning', 'Planning an adventure'), ('booking', 'An existing booking request'), ('general', 'Something else')], max_length=20)),
                ('message', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('mountains', 'Mountains'), ('lakes', 'Lakes & Adventure'), ('culture', 'Culture'), ('wildlife', 'Wildlife')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
                ('static_image', models.CharField(choices=[('images/everest.jpg', 'Everest'), ('images/annapurna.jpg', 'Annapurna'), ('images/popular/uppermustang.jpg', 'Mustang'), ('images/popular/lakeside.jpg', 'Pokhara Lake'), ('images/blog/paragliding.jpg', 'Paragliding'), ('images/blog/temple.jpg', 'Temple'), ('images/blog/village.jpg', 'Himalayan Village'), ('images/chitwan.jpg', 'Chitwan')], default='images/everest.jpg', help_text='Used when no image is uploaded.', max_length=150)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery photos',
                'ordering': ('ordering', 'title', 'pk'),
            },
        ),
    ]
