# Generated by Django 6.0.7 on 2026-09-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='region',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
