# Generated by Django 6.0.7 on 2026-10-06 04:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0002_region_image_region_image_alt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submission_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('adventure_title', models.CharField(max_length=200)),
                ('duration_days', models.PositiveIntegerField()),
                ('travel_date', models.DateField()),
                ('travellers', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9\\s().-]{6,24}$', 'Enter a valid phone number, including your country code.')])),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Under Review'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('team_notes', models.TextField(blank=True, help_text='Internal notes; not shown to travellers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='adventures.adventure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_bo_user_id_c051a0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('travellers__gte', 1)), name='booking_travellers_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='booking_price_nonnegative')],
            },
        ),
    ]
